version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: mrt-portfolio-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=your-jwt-secret-here
      - JWT_EXPIRES_IN=1h
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    working_dir: /app/backend
    command: npm run dev
    depends_on:
      - database
    networks:
      - portfolio-network

  # Frontend Development Server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: mrt-portfolio-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    networks:
      - portfolio-network

  # SQLite Database (for development)
  database:
    image: alpine:latest
    container_name: mrt-portfolio-db
    volumes:
      - ./backend/database:/data
    command: sh -c "echo 'Database volume mounted' && tail -f /dev/null"
    networks:
      - portfolio-network

  # Nginx Reverse Proxy (for production-like setup)
  nginx:
    image: nginx:alpine
    container_name: mrt-portfolio-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - portfolio-network
    profiles:
      - production

  # Redis Cache (optional)
  redis:
    image: redis:alpine
    container_name: mrt-portfolio-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - portfolio-network
    profiles:
      - production

  # Monitoring (optional)
  monitoring:
    image: prom/prometheus:latest
    container_name: mrt-portfolio-monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - portfolio-network
    profiles:
      - production

networks:
  portfolio-network:
    driver: bridge

volumes:
  redis-data: 